### ISSUE TITLE
棚・引き出し・ドアのアウトラインが残ってしまう

### ISSUE THREAD

**Issue by Hiraki-Shunsuke** [InnovaGameCreate/mythos-encounter#106]
マウスオーバー時にアクティブになるアウトラインが、カーソルを外した状態でも残ってしまうバグがある。
[条件]
1. StageIntractのついたオブジェクトにカーソルを合わせる
2. そのオブジェクトからカーソルを外さず他のStageIntractのついたオブジェクトにカーソルを合わせる
3. 元のオブジェクトのアウトラインが残る

https://github.com/InnovaGameCreate/mythos-encounter/assets/86967899/52d69c0b-4b72-46ae-a9d1-56c1a8e354f9

**Comment by tibigamePoppo** [comment]
対応しておきます

**Comment by tibigamePoppo** [comment]
https://github.com/InnovaGameCreate/mythos-encounter/pull/108
上記ブランチで修正を行いました
