### ISSUE TITLE
プレイヤーの死体が空中に浮いている

### ISSUE THREAD

**Issue by Tyunousause** [InnovaGameCreate/mythos-encounter#121]
プレイヤーが敵に殺された際、壁際にいると空中に死体が固定されます

**Comment by IwamotoHinata** [comment]
・ダッシュ後、一定時間ダッシュできないようにする（グリッチ）
・Shiftキー押した後にASDキーを押しても反応しない

これらと同じブランチで修正します

**Comment by IwamotoHinata** [comment]
#123 で修正
