### ISSUE TITLE
すでにアイテムが格納されているスロットにカーソルを合わせてアイテムを拾うとUIが表示され続ける

### ISSUE THREAD

**Issue by Tyunousause** [InnovaGameCreate/mythos-encounter#136]
![スクリーンショット (1501)](https://github.com/user-attachments/assets/153ecbe3-2f0e-4f62-b881-393053ee38a5)
こんな感じ

**Comment by Tyunousause** [comment]
ブランチはfeatire/player/item/dollだけどbandageでも起きた

**Comment by IwamotoHinata** [comment]
#138 修正しました
