### ISSUE TITLE
Playerや脱出アイテムなどの沸く量が2倍になるときがある

### ISSUE THREAD

**Issue by IwamotoHinata** [InnovaGameCreate/mythos-encounter#151]
題名の通りです。
2倍になるときと、ならないときがあります

**Comment by IwamotoHinata** [comment]
![スクリーンショット 2024-08-09 000017](https://github.com/user-attachments/assets/83175ad6-03e7-40a6-8719-38061b899042)

**Comment by tibigamePoppo** [comment]
https://github.com/InnovaGameCreate/mythos-encounter/pull/153
こちらで修正しました
