### ISSUE TITLE
MAPの表示順について

### ISSUE THREAD

**Issue by tibigamePoppo** [InnovaGameCreate/mythos-encounter#159]
現状の問題：緑のキャラクターアイコンの上に黒の横線が入る
理想：キャラクターアイコンが一番上のレイヤー
![image](https://github.com/user-attachments/assets/9d04ea43-8405-4804-bf98-3bfe60336207)

**Comment by IwamotoHinata** [comment]
#160 修正しました。
そもそも横線の表示を消し忘れてました...
