### ISSUE TITLE
Escape Itemがとれない

### ISSUE THREAD

**Issue by Tyunousause** [InnovaGameCreate/mythos-encounter#17]
Escape Itemが取れない
deberopブランチ。IngameStageシーン。Marge Pull Request#11

**Comment by IwamotoHinata** [comment]
Marge Pull Request#12以降だと取得できると思います。

**Comment by tibigamePoppo** [comment]
Ingameは統合作業が完了していないため、今はEscape Itemが取れないっぽいです。
もし確認が必要ならIngame_Managerの環境でテストする必要がありそう
