### ISSUE TITLE
NavMeshのエラーがregenarateStageが成功するまでずっと出続ける

### ISSUE THREAD

**Issue by Tyunousause** [InnovaGameCreate/mythos-encounter#176]
#713以降のdevelopにて確認。どこから発生していたかはわからないが以前は出ていなかったはず
RuntimeNavMeshBuilder: Source mesh Mini_Table _LOD0 does not allow read access. This will work in playmode in the editor but not in player
UnityEngine.AI.NavMeshBuilder:BuildNavMeshData (UnityEngine.AI.NavMeshBuildSettings,System.Collections.Generic.List`1<UnityEngine.AI.NavMeshBuildSource>,UnityEngine.Bounds,UnityEngine.Vector3,UnityEngine.Quaternion)
Unity.AI.Navigation.NavMeshSurface:BuildNavMesh () (at ./Library/PackageCache/com.unity.ai.navigation@1.1.5/Runtime/NavMeshSurface.cs:267)
Scenes.Ingame.Stage.StageGenerator/<ReGenerateWall>d__33:MoveNext () (at Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs:172)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1<Scenes.Ingame.Stage.StageGenerator/<ReGenerateWall>d__33>:Run () (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Assets/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<object>:TrySetResult (object) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayPromise:MoveNext () (at Assets/Plugins/UniTask/Runtime/UniTask.Delay.cs:763)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:104)

**Comment by tibigamePoppo** [comment]
Mini_Table _LOD0 does not allow read accessがエラー分やから、アセットを入れ直して、アクセスの許可を入れたいけるんじゃね。

**Comment by tibigamePoppo** [comment]
https://github.com/InnovaGameCreate/mythos-encounter/pull/178
これで修正しました
