### ISSUE TITLE
HP,スタミナのバーがいじれる

### ISSUE THREAD

**Issue by tibigamePoppo** [InnovaGameCreate/mythos-encounter#62]
HPとスタミナを現在スライダーで実装しており、クリックすると値が変更できるため、クリックしても値が変更できないようにする

**Comment by IwamotoHinata** [comment]
TempPlayerMoveの中にマウスカーソルを真ん中で固定＆非表示にする処理があるので、問題はないと思います。
isCurcleSettingというBool値をUnityのInspecterの方でTrueにすると上記の処理が実行されます

**Comment by tibigamePoppo** [comment]
了解しました、クローズさせます
