### ISSUE TITLE
装飾品の表示がバグる

### ISSUE THREAD

**Issue by IwamotoHinata** [InnovaGameCreate/mythos-encounter#72]
https://github.com/InnovaGameCreate/mythos-encounter/assets/86921212/93656df9-4c53-4c5e-a14f-66b4a784fd81

2x2Corridor_HHというプレハブの装飾品の表示が動画のようにバグっています。
これはこれで恐怖を与える演出としてはいいかも？

**Comment by Hiraki-Shunsuke** [comment]
#119 で修正済み
